---
- name: Create user {{ item.username }}
  user:
    name: "{{ item.username }}"
    shell: /bin/bash
    group: users
    groups: "{{ 'sudo' if item.sudoer is defined else '' }}"
    append: true                                                # --> user is not removed from any other group
    password: "{{ item.password|password_hash('sha512', item.password_salt) }}"
  loop: "{{ system_users }}"

- name: Set authorized key for user {{ item.username }}
  authorized_key:
    user: "{{ item.username }}"
    state: present
    key: "{{ item.public_key }}"
  loop: "{{ system_users }}"

- name: Force usual sudoers to enter their password
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) ALL'
    validate: 'visudo -cf %s'

- name: Allow certain users sudo without a password
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: "{{ item.username }} ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'
  loop: "{{ system_users }}"
  when: item.no_sudo_passwd is defined
