---
# Uses variable: allow_user
- name: Check if AllowUsers directive is present at all
  lineinfile:
    dest: "{{ ssh_sshd_config }}"
    regexp: "^#?AllowUsers.*$"
    state: absent
  check_mode: true
  changed_when: false
  register: allowusers_line

- name: Make sure AllowUsers directive is present at all
  lineinfile:
    dest: "{{ ssh_sshd_config }}"
    line: 'AllowUsers'
  when: not allowusers_line.found
  notify:
    - restart sshd

- name: Check if {{ allow_user }} is already contained in AllowUsers
  lineinfile:
    dest: "{{ ssh_sshd_config }}"
    regexp: "^#?AllowUsers .*{{ allow_user }}.*$"
    state: absent
  check_mode: true
  changed_when: false
  register: permission_already

- name: Add {{ allow_user }} to ssh allowed users to if not already
  lineinfile:
    dest: "{{ ssh_sshd_config }}"
    backrefs: true
    regexp: "^#?AllowUsers(.*)$"
    line: 'AllowUsers\1 {{ allow_user }}'
  when: not permission_already.found
  notify:
    - restart sshd
